In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path = r"H:\PYTHON\Etapa3\AnaliseTabela4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [3]:
dados_brutos = pd.read_excel(path, header=2)

In [4]:
print(dados_brutos)

      Unnamed: 0                                                 UF  COD. UF  \
0            NaN                                                 RO     11.0
1            NaN                                                 RO     11.0
2            NaN                                                 RO     11.0
3            NaN                                                 RO     11.0
4            NaN                                                 RO     11.0
...          ...                                                ...      ...
5569         NaN                                                 DF     53.0
5570         NaN                                                NaN      NaN
5571         NaN  Nota: Para o cálculo das taxas de crescimento ...      NaN
5572         NaN                                                NaN      NaN
5573         NaN  Fonte: IBGE. Diretoria de Pesquisas - DPE -  C...      NaN

      COD. MUNIC      NOME DO MUNICÍPIO  População Município 2010\n(Sinopse)  \
0           15.0  Alta Floresta D'Oeste                              24392.0
1           23.0              Ariquemes                              90353.0
2           31.0                 Cabixi                               6313.0
3           49.0                 Cacoal                              78574.0
4           56.0             Cerejeiras                              17029.0
...          ...                    ...                                  ...
5569       108.0               Brasília                            2570160.0
5570         NaN                    NaN                                  NaN
5571         NaN                    NaN                                  NaN
5572         NaN                    NaN                                  NaN
5573         NaN                    NaN                                  NaN

      População 2010 (Alterações de Limites até 2022)1  População Censo 2022
0                                              24392.0               21494.0
1                                              90353.0               96833.0
2                                               6313.0                5351.0
3                                              78574.0               86887.0
4                                              17029.0               15890.0
...                                                ...                   ...
5569                                         2572159.0             2817381.0
5570                                               NaN                   NaN
5571                                               NaN                   NaN
5572                                               NaN                   NaN
5573                                               NaN                   NaN

[5574 rows x 8 columns]

In [5]:
dados_limpos = dados_brutos.dropna(subset=["UF"])

In [6]:
col_2010 = "População 2010 (Alterações de Limites até 2022)1"
col_2022 = "População Censo 2022"

dados_limpos[col_2010] = pd.to_numeric(dados_limpos[col_2010], errors='coerce')
dados_limpos[col_2022] = pd.to_numeric(dados_limpos[col_2022], errors='coerce')

In [7]:
variavel_a_criar = (
    dados_limpos.groupby("UF")[[col_2010, col_2022]]
    .sum()
    .reset_index()
)

variavel_a_criar["Crescimento_Absoluto"] = variavel_a_criar[col_2022] - variavel_a_criar[col_2010]
tabela_estado_ordenada = variavel_a_criar.sort_values(by="Crescimento_Absoluto", ascending=False)

tabela_estado_ordenada.to_csv("populacao_estado_crescimento.csv", index=False)

In [8]:
dados_limpos["Crescimento_Absoluto"] = dados_limpos[col_2022] - dados_limpos[col_2010]
tabela_municipio_ordenada = dados_limpos.sort_values(by="Crescimento_Absoluto", ascending=False)

In [9]:
colunas_finais = ["UF", "NOME DO MUNICÍPIO", col_2010, col_2022, "Crescimento_Absoluto"]
tabela_municipio_final = tabela_municipio_ordenada[colunas_finais]

In [10]:
tabela_municipio_final.to_csv("populacao_municipio_crescimento.csv", index=False)

print("Exercício concluído! Os arquivos CSV foram salvos na pasta do projeto.")

Exercício concluído! Os arquivos CSV foram salvos na pasta do projeto.

In [11]:

print("TOP 5 ESTADOS QUE MAIS CRESCERAM")
display(tabela_estado_ordenada.head())

print("\n" + "="*50 + "\n")


print("TOP 5 MUNICÍPIOS QUE MAIS CRESCERAM")
display(tabela_municipio_final.head())

TOP 5 ESTADOS QUE MAIS CRESCERAM

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento_Absoluto
27,SP,41262199.0,44411238.0,3149039.0
25,SC,6248436.0,7610361.0,1361925.0
9,GO,6001789.0,7056495.0,1054706.0
19,PR,10444526.0,11444380.0,999854.0
11,MG,19597330.0,20539989.0,942659.0

==================================================

TOP 5 MUNICÍPIOS QUE MAIS CRESCERAM

,UF,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento_Absoluto
111,AM,Manaus,1802014.0,2063689.0,261675.0
5569,DF,Brasília,2572159.0,2817381.0,245222.0
3829,SP,São Paulo,11253503.0,11451999.0,198496.0
3848,SP,Sorocaba,586816.0,723682.0,136866.0
5417,GO,Goiânia,1301912.0,1437366.0,135454.0